"""keys changed

Revision ID: 2c99ce62ca4d
Revises: bb3be439f06e
Create Date: 2021-04-21 21:51:12.567432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c99ce62ca4d'
down_revision = 'bb3be439f06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('crypto_prices_min_unadj_crypto_id_fkey', 'crypto_prices_min_unadj', type_='foreignkey')
    op.create_foreign_key(None, 'crypto_prices_min_unadj', 'crypto', ['crypto_id'], ['ticker'])
    op.create_unique_constraint(None, 'vendor', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor', type_='unique')
    op.drop_constraint(None, 'crypto_prices_min_unadj', type_='foreignkey')
    op.create_foreign_key('crypto_prices_min_unadj_crypto_id_fkey', 'crypto_prices_min_unadj', 'forex', ['crypto_id'], ['ticker'])
    # ### end Alembic commands ###
