"""empty message

Revision ID: 37da9d8f3cab
Revises: 2c99ce62ca4d
Create Date: 2021-04-26 03:05:55.109068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37da9d8f3cab'
down_revision = '2c99ce62ca4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
