"""empty message

Revision ID: 19fade8eff61
Revises: 9af3a4924f4a
Create Date: 2021-10-01 22:37:20.374622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fade8eff61'
down_revision = '9af3a4924f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
