"""empty message

Revision ID: e80ee8684134
Revises: 19fade8eff61
Create Date: 2021-10-01 23:15:26.317432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e80ee8684134'
down_revision = '19fade8eff61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('ask_exchange', sa.Enum('A', 'B', 'C', 'D', 'E', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'NA', name='exch'), nullable=True))
    op.drop_column('quotes', 'ask_exchanges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('ask_exchanges', postgresql.ENUM('A', 'B', 'C', 'D', 'E', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', name='exch'), autoincrement=False, nullable=True))
    op.drop_column('quotes', 'ask_exchange')
    # ### end Alembic commands ###
